version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "cargo"
    directory: "/native/mail_parser_nif"
    schedule:
      interval: "monthly"

  - package-ecosystem: mix
    directory: "/"
    schedule:
      interval: "monthly"
